/*
  AUTOGENERATED FILE. DON'T EDIT DIRECTLY

  This file was generated by tuple.extensions.generator.kts
*/

package com.nekomatic.katarynka.arrow

import arrow.core.Tuple2
import arrow.syntax.collections.plus

fun <A, B, C> Tuple2<Tuple2<A, B>, C>.flatten() = this.a + this.b
fun <A, B, C, D> Tuple2<Tuple2<Tuple2<A, B>, C>, D>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E> Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H, I> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>, I>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H, I, J> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>, I>, J>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H, I, J, K> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>, I>, J>, K>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H, I, J, K, L> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>, I>, J>, K>, L>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H, I, J, K, L, M> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>, I>, J>, K>, L>, M>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>, I>, J>, K>, L>, M>, N>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>, I>, J>, K>, L>, M>, N>, O>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>, I>, J>, K>, L>, M>, N>, O>, P>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>, I>, J>, K>, L>, M>, N>, O>, P>, Q>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>, I>, J>, K>, L>, M>, N>, O>, P>, Q>, R>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>, I>, J>, K>, L>, M>, N>, O>, P>, Q>, R>, S>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>, I>, J>, K>, L>, M>, N>, O>, P>, Q>, R>, S>, T>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>, I>, J>, K>, L>, M>, N>, O>, P>, Q>, R>, S>, T>, U>.flatten() = this.a.flatten() + this.b
fun <A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V> Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<Tuple2<A, B>, C>, D>, E>, F>, G>, H>, I>, J>, K>, L>, M>, N>, O>, P>, Q>, R>, S>, T>, U>, V>.flatten() = this.a.flatten() + this.b
