/*******************************************************************************
 * The MIT License
 *
 * Copyright (c)  2018.  nekomatic.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 *
 ******************************************************************************/

import java.io.File

val notice = """/*
  AUTOGENERATED FILE. DON'T EDIT DIRECTLY

  This file was generated by tuple.extensions.generator.kts
*/

"""
val package_ = "com.nekomatic.katarynka.arrow"
val maxTuple = 21

val availableLetters = ('a'..'z').toList().map { it.toString() }

val fileContent = StringBuilder()

val imports = """
import arrow.core.Tuple2
import arrow.syntax.collections.plus
""".trimIndent()

fileContent.append(notice)
fileContent.append("package $package_")
fileContent.append("\n\n")
fileContent.append(imports)
fileContent.append("\n\n")

fileContent.append("fun <A, B, C> Tuple2<Tuple2<A, B>, C>.flatten() = this.a + this.b")
fileContent.append("\n")

for (i in 3..maxTuple) {

    val letters = availableLetters.take(i + 1)

    val diamond1 = "<${letters.joinToString { it.toUpperCase() }}>"

    val source = letters.drop(2).asSequence().fold("Tuple2<A, B>") { acc, n -> "Tuple2<${acc}, ${n.toUpperCase()}>" }
    fileContent.append("fun $diamond1 $source.flatten() = this.a.flatten() + this.b")
    fileContent.append("\n")
}

val fileLocation = "./src/main/kotlin/com/nekomatic/katarynka/arrow/tupleExtensions.kt"

File(fileLocation).writeText(fileContent.toString())